name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 0.5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: jdk
          architecture: x64
      - run: javac *.java
<<<<<<< HEAD
      - run: java StalactiteFightNight
=======
      - run: java StalactiteFightNight 2718 <test_input.txt
>>>>>>> 3bf5a5193a864d117c5fdca817ca62c6669d7817
      - run: javadoc -d out *.java

